/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c8aae9b6-44a1-4006-a22c-ddcd2362ed5c",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_3a6GGlIE4",
    "aws_user_pools_web_client_id": "46lpve5eaosujl4c0osgj58ssu",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://o2qk2yul4jchtfjmzcr5gnblte.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4t5pc24vojda5inankrbex64ua"
};


export default awsmobile;
